### ISSUE TITLE
Plus1Plus1Counters shouldn't be a thing

### ISSUE THREAD

**Issue by andrewljohnson** [midrange/rogue#29]
sometimes you get +0/+1 counters, or 1/+0 counters

**Comment by andrewljohnson** [comment]
What will we do for like: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=2938

**Comment by lacker** [comment]
In some way it needs to represent each counter individually. Either &Counter{Power: 0, Toughness: 1} or Plus0Plus1Counters, I dunno which will be simpler. Probably the former, but +1/+1 and -1/-1 might have to be special cases due to the cancellation rule.

see: https://mtg.gamepedia.com/%2B1/%2B1_counter
