### ISSUE TITLE
Discuss: ManaCost needs to be able to be null

### ISSUE THREAD

**Issue by andrewljohnson** [midrange/rogue#3]
For lands, it's null. For Ornithopter, it's 0.

Lands could have it be -1.

**Comment by lacker** [comment]
I think it eventually needs to be some other struct instead of an int to represent the difference between 1G and 1R and so on. And then that struct can have some way to specify "no mana cost". For lands you can check IsLand, the trickier thing is that there is no way to express that e.g. Ancestral Visions cannot be cast at all. For now leaving it at 0 seems to be just as good as making it -1 - I mean the CMC of a land is technically 0 after all.
